# Generated by Django 2.2.3 on 2019-09-15 18:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5, 'Name must be greater than 5 characters')], verbose_name='Name of the Game')),
                ('descr', models.TextField(null=True, verbose_name='Game Description (if applicable)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_owned', to=settings.AUTH_USER_MODEL)),
                ('players', models.ManyToManyField(related_name='games_played', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short', models.CharField(max_length=1, validators=[django.core.validators.MinLengthValidator(1, 'Name must be greater than 1 character')])),
                ('long', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(3, 'Name must be greater than 3 characters')])),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(1, 'Name must be greater than 1 character')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hfgame.Game')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hfgame.GameStatus'),
        ),
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_won', to=settings.AUTH_USER_MODEL),
        ),
    ]
