# Generated by Django 2.2.3 on 2019-09-29 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hfgame', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='descr',
            field=models.TextField(blank=True, null=True, verbose_name='Game Description (if applicable)'),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hfgame.GameStatus'),
        ),
    ]
