# Generated by Django 2.2.4 on 2019-10-24 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hfgame', '0005_game_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='players',
        ),
    ]
