# Generated by Django 2.2.4 on 2019-10-26 23:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hfgame', '0006_remove_game_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='winner',
        ),
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='games_won', to=settings.AUTH_USER_MODEL),
        ),
    ]
