# Generated by Django 2.2.4 on 2019-10-31 14:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hfgame', '0007_auto_20191026_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.ManyToManyField(blank=True, default=None, related_name='games_won', to=settings.AUTH_USER_MODEL),
        ),
    ]
